import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/NavBar";
import { AuthProvider } from "@/components/AuthProvider";
import Footer from "@/components/Footer";
import { KorpaProvider } from "./context/KorpaContext";
import "tailwindcss"
import { Quicksand } from 'next/font/google';
import { Roboto } from 'next/font/google';
import { Lexend_Deca } from 'next/font/google';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const quicksand = Quicksand({ 
  variable: "--font-quicksand",
  subsets: ['latin', 'latin-ext'], 
  weight: ['400','700'], 
});

const roboto = Roboto({ 
  variable: "--font-roboto",
  subsets: ['latin', 'latin-ext'], 
  weight: ['400','700'], 
});

const lexendDeca = Lexend_Deca({ 
  variable: "--font-lexenddeca",
  subsets: ['latin', 'latin-ext'], 
  weight: ['500','700'], 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.variable} ${quicksand.variable} antialiased flex flex-col min-h-screen`}
      >


       <main className="flex-1 min-h-screen">
        <AuthProvider>
          <KorpaProvider>
            <NavBar/>
            {children}
            <Footer></Footer>
          </KorpaProvider>
        </AuthProvider>
        </main>
        

      </body>
    </html>
  );

}
