name: build-test
on: 
  push:
    branches: 
      - 'develop'

defaults: 
  run:
    shell: 'bash'

jobs:
  testing:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'build-test'
        run: |-
            docker build .